// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"star/internal/dao/internal"
)

// pyFundDao is the data access object for the table py_fund.
// You can define custom methods on it to extend its functionality as needed.
type pyFundDao struct {
	*internal.PyFundDao
}

var (
	// PyFund is a globally accessible object for table py_fund operations.
	PyFund = pyFundDao{internal.NewPyFundDao()}
)

// Add your custom methods and functionality below.
