// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"star/internal/dao/internal"
)

// pyHadDao is the data access object for the table py_had.
// You can define custom methods on it to extend its functionality as needed.
type pyHadDao struct {
	*internal.PyHadDao
}

var (
	// PyHad is a globally accessible object for table py_had operations.
	PyHad = pyHadDao{internal.NewPyHadDao()}
)

// Add your custom methods and functionality below.
