// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"star/internal/dao/internal"
)

// pyHtDao is the data access object for the table py_ht.
// You can define custom methods on it to extend its functionality as needed.
type pyHtDao struct {
	*internal.PyHtDao
}

var (
	// PyHt is a globally accessible object for table py_ht operations.
	PyHt = pyHtDao{internal.NewPyHtDao()}
)

// Add your custom methods and functionality below.
