// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"star/internal/dao/internal"
)

// pyTDao is the data access object for the table py_t.
// You can define custom methods on it to extend its functionality as needed.
type pyTDao struct {
	*internal.PyTDao
}

var (
	// PyT is a globally accessible object for table py_t operations.
	PyT = pyTDao{internal.NewPyTDao()}
)

// Add your custom methods and functionality below.
